---

- name: Install jMeter
  unarchive:
    src=http://archive.apache.org/dist/jmeter/binaries/apache-jmeter-{{ jmeter_version }}.tgz
    dest=/usr/local/src
    remote_src=yes
    creates=/usr/local/src/apache-jmeter-{{ jmeter_version }}
  tags:
    - jmeter
